# Generated by Django 2.1.13 on 2019-10-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecompy_api', '0004_auto_20191030_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='modified_at',
        ),
    ]
